FROM minio/mint

# This is from the mint test suite -->
#   minio/mint/build/minio-go/install.sh
# I have minio and minio-go checked out into the same parent folder
COPY minio-go /mint/run/core/minio-go/main.go
COPY aws-sdk-go /mint/run/core/aws-sdk-go/
